//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locamer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sejour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sejour()
        {
            this.info_option = new HashSet<info_option>();
            this.mobile_home = new HashSet<mobile_home>();
        }
    
        public int id_sejour { get; set; }
        public System.DateTime date_debut { get; set; }
        public System.DateTime date_fin { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> id_tsejour { get; set; }
        public Nullable<int> id_option { get; set; }

        public double prix_sejour { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<info_option> info_option { get; set; }
        public virtual type_sejour type_sejour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobile_home> mobile_home { get; set; }

        public double CalculPrix()
        {
            double prixTarif = 0;
            double prixOption = 0;
            foreach (var emplacement in mobile_home)
                prixTarif += emplacement.tarif.prix_jour * (double)this.NbreJours();
            foreach (var option in info_option)
                prixOption += option.option.prix_jour;
            // double prix = ((prixOption + prixTarif) + NbreJours()) * type_sejour.coeff;
            return prixTarif;
        }

        public int NbreJours()
        {
            TimeSpan jours = date_fin - date_debut;
            int duree = (int)jours.TotalDays;
            if (duree < 1)
                duree = 1;
            return duree;
        }
    }
}
